name: Deploy to DigitalOcean
on:
  push:
    branches:
      - master  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.MASTER_TOKEN }}
          app_name: "spring-boot-deployment"  # Replace with your app name
          app_spec_location: ".do/app.yaml"  # Path to your app spec file